---
title: "Mapping Tutorial Map"
author: "Suvan Chatakondu"
date: '2022-07-01'
description: "This is a plot that I have made using US Census Data"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidycensus)
library(ggthemes)
library(tigris)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rural <- get_decennial(geography = "state", variables = c("P001001", "P002005"), year = 2010, output = "wide", geometry = TRUE)

rural  %>% 
  filter(! NAME %in% c("Alaska", "Hawaii", "Puerto Rico")) |> 
  mutate(prop_rural = P002005/P001001) %>% 
  ggplot(aes(fill = 100*P002005/P001001)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma",
                     direction = -1) +
  labs(title = "Rural geography of the United States",
       caption = "Source: Census 2010",
       fill = 'Percent Rural') +
  theme_void()
```

```{r}
rural_shifted <- get_decennial(geography = "state", variables = c("P001001", "P002005"), year = 2010, output = "wide", geometry = TRUE)

rural_shifted  %>% 
  shift_geometry() |> 
  mutate(prop_rural = P002005/P001001) %>% 
  ggplot(aes(fill = 100*P002005/P001001)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma",
                     direction = -1) +
  labs(title = "Rural geography of the United States",
       caption = "Source: Census 2010",
       fill = 'Percent Rural') +
  theme_void()
```

